# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-04 17:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField(editable=False)),
                ('action', models.CharField(choices=[('MARKDONE', 'MARKDONE'), ('MARKNOTDONE', 'MARKNOTDONE')], max_length=127)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=127)),
                ('status', models.CharField(choices=[('DONE', 'DONE'), ('NOTDONE', 'NOTDONE'), ('DELETED', 'DELETED')], default='UNDONE', max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task'),
        ),
    ]
